import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import AuthProvider from "@/context/AuthProvider";
import Chat from "@/components/Chat";
import Providers from "@/components/Providers";
import { Toaster } from "@/components/ui/toaster";
import { Analytics } from "@vercel/analytics/react"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Singularity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" h-full bg-black ">
      <AuthProvider>
     <Providers>
     <body className={cn(" relative h-full font-sans antialiased", inter.className)}>
        <main className=" relative flex flex-col min-h-screen">
          <Analytics/>
          <Navbar/>
        <div className=" flex-grow flex-1">{children}</div>
        <Chat/>
        </main>
        <Toaster />
      </body>
     </Providers>
      </AuthProvider>
    </html>
  );
}
